package com.example.lib;

public class Test2 {
    String[] douhao = new String[]{"，", ". ", "."};

    public static void main(String[] args) {
        String ap_array_auto_parking = "*;Treten Sie auf die Bremse und starten Sie;Das Parken hat begonnen. Bitte lösen Sie das Bremspedal;Parken.... Überprüfen Sie sicherheitshalber die Umgebung;Es sind Hindernisse im Weg;Parken ist aus. Bitte übernehmen Sie das Fahrzeug;Parken beendet;Parken ist aus;Losfahren.... Überprüfen Sie sicherheitshalber die Umgebung;Es sind Hindernisse im Weg;Losfahren ist aus;Losfahren beendet;Losfahren hat begonnen[comma] Bitte lösen Sie das Bremspedal;Parken angehalten. Bitte bestätigen Sie die Sicherheit und fahren Sie fort;Losfahren angehalten. Bitte bestätigen Sie die Sicherheit und fahren Sie fort;Losfahren ist möglich;*;Rückwärtsfahren.... Überprüfen Sie sicherheitshalber die Umgebung;Fahren Sie langsamer als 24km/h. Kann keine Parkplätze erkennen;Bitte fahren Sie weiter. Suche nach Parkplätzen...;Parkplatz gefunden. Halten Sie das Fahrzeug an[comma] wenn Sie parken müssen; eine Ausnahme ist eingetreten. Bitte wenden Sie sich an den Kundenservice; Treten Sie auf die Bremse und starten Sie; Treten Sie auf die Bremse[comma] wenn Sie parken müssen; Bitte treten Sie auf das Bremspedal; Steiler Abhang. Die intelligente Einparkhilfe ist nicht verfügbar; Sie ist angehalten. Wenn Sie weiterfahren müssen[comma] lassen Sie das Bremspedal los;Rückwärtsfahren.... Überprüfen Sie sicherheitshalber die Umgebung;*;*;*;*;*;Beachten Sie[comma] dass das Risiko von Kratzern besteht;Überprüfen Sie[comma] ob genügend Platz zum Parken vorhanden ist...;Es gibt ein Hindernis auf dem Parkplatz. Versuchen Sie einen anderen;Bitte treten Sie auf das Bremspedal";
        String ap_array_auto_parkin2 = "*;Treten Sie auf die Bremse und starten Sie;Das Parken hat begonnen. Bitte lösen Sie das Bremspedal;Parken.... Überprüfen Sie sicherheitshalber die Umgebung;Es sind Hindernisse im Weg;Parken ist aus. Bitte übernehmen Sie das Fahrzeug;Parken beendet;Parken ist aus;Losfahren.... Überprüfen Sie sicherheitshalber die Umgebung;Es sind Hindernisse im Weg;Losfahren ist aus;Losfahren beendet;Losfahren hat begonnen[comma] Bitte lösen Sie das Bremspedal;Parken angehalten. Bitte bestätigen Sie die Sicherheit und fahren Sie fort;Losfahren angehalten. Bitte bestätigen Sie die Sicherheit und fahren Sie fort;Losfahren ist möglich;*;Rückwärtsfahren.... Überprüfen Sie sicherheitshalber die Umgebung;Fahren Sie langsamer als 24km/h. Kann keine Parkplätze erkennen;Bitte fahren Sie weiter. Suche nach Parkplätzen...;Parkplatz gefunden. Halten Sie das Fahrzeug an[comma] wenn Sie parken müssen; eine Ausnahme ist eingetreten. Bitte wenden Sie sich an den Kundenservice; Treten Sie auf die Bremse und starten Sie; Treten Sie auf die Bremse[comma] wenn Sie parken müssen; Bitte treten Sie auf das Bremspedal; Steiler Abhang. Die intelligente Einparkhilfe ist nicht verfügbar; Sie ist angehalten. Wenn Sie weiterfahren müssen[comma] lassen Sie das Bremspedal los;Rückwärtsfahren.... Überprüfen Sie sicherheitshalber die Umgebung;*;*;*;*;*;Beachten Sie[comma] dass das Risiko von Kratzern besteht;Überprüfen Sie[comma] ob genügend Platz zum Parken vorhanden ist...;Es gibt ein Hindernis auf dem Parkplatz. Versuchen Sie einen anderen;Bitte treten Sie auf das Bremspedal";
        String ap_array_auto_parking3 = "*;请踩住刹车，点击开始;泊车开始，请松开刹车;泊车中，请注意周围环境安全;有障碍物阻挡;泊车已退出，请接管车辆;泊车已完成;泊车已退出;泊出中，请注意周围环境安全;有障碍物阻挡;泊出已退出;泊出已完成;泊出开始，请松开刹车;泊车暂停，请确认安全后点击继续;泊出暂停，请确认安全后点击继续;点击开始可以帮你泊出;*;倒车中，请注意周围环境安全;当前车速高于24km/h，无法识别车位;请往前开，正在找车位;找到车位，如需泊入请停车;发生异常，请联系客服处理;请踩住刹车，点击开始;如需泊入，请踩刹车;请踩刹车;坡度过大，智能辅助泊车不可用;已暂停，如需恢复可松开刹车;倒车中，请注意周围环境安全;*;*;*;*;*;请注意后方有剐蹭风险;正在探测车位内空间是否充足;车位内有障碍物，换一个试试吧;请踩刹车";


        String ap_array_auto_parkingAR = "*;الرجاء الضغط على الفرامل وانقر فوق ابدأ;يبدأ ركن السيارة، يرجى تحرير الفرامل;أثناء ركن السيارة، يرجى الانتباه إلى سلامة البيئة المحيطة.;هناك عوائق تسد الطريق;لقد تم الخروج من موقف السيارات، يرجى تولي السيارة;وقوف السيارات الانتهاء;لقد تم الخروج من موقف السيارات;عند ركن السيارة، يرجى الانتباه لسلامة البيئة المحيطة.;هناك عوائق تسد الطريق;لقد تم الخروج من موقف السيارات;اكتمل وقوف السيارات;عند بدء ركن السيارة، يرجى تحرير الفرامل;تم تعليق مواقف السيارات، يرجى التأكد من أنها آمنة والنقر للمتابعة.;تم تعليق مواقف السيارات، يرجى تأكيد السلامة والنقر للمتابعة.;انقر فوق \"ابدأ\" لمساعدتك في ركن السيارة;*;عند الرجوع للخلف، يرجى الانتباه إلى سلامة البيئة المحيطة;سرعة السيارة الحالية أعلى من 24 كم/ساعة ولا يمكن تحديد مكان ركن السيارة.;يرجى القيادة للأمام بحثًا عن مكان لوقوف السيارات;ابحث عن مكان لوقوف السيارات، يرجى ركن السيارة إذا كنت بحاجة إلى ركن السيارة.;حدث استثناء، يرجى الاتصال بخدمة العملاء للتعامل معه.;الرجاء الضغط على الفرامل وانقر فوق ابدأ;إذا كنت بحاجة إلى الوقوف، يرجى الضغط على الفرامل؛يرجى الضغط على الفرامل;المنحدر كبير جدًا ولا تتوفر المساعدة الذكية في ركن السيارة.;توقف مؤقتًا، إذا كنت بحاجة إلى الاستئناف، يمكنك تحرير الفرامل;عند الرجوع للخلف، يرجى الانتباه إلى سلامة البيئة المحيطة;*;*;*;*;*;يرجى ملاحظة أن هناك خطر حدوث خدوش من الخلف;اكتشاف ما إذا كانت هناك مساحة كافية في مكان وقوف السيارات;هناك عوائق في مكان وقوف السيارات، حاول واحدة أخرى.;الرجاء استخدام الفرامل";
        String ap_array_auto_parking4 ="[&]Please press the brake, click start[&], release the brake, start parking[&], please pay attention to the safety of the surrounding environment[&]Parking pauses, there are obstacles blocking[&]Parking has exited, please take over the vehicle[&]Parking is completed[&]Parking has exited[&], please pay attention to the safety of the surrounding environment[&]Parking pauses, there are obstacles blocking[&]Parking has exited[&]Parking is completed[&], please release the brake, start parking[&], confirm safety, click to continue parking[&], confirm safety, Click to continue parking[&]Click to start, help you park out[&][&]While reversing, please pay attention to the safety of the surrounding environment[&]The speed is too fast, and the parking space cannot be recognized at the moment[&][&]Find the parking space. If you need to park, please park[&]Parking is temporarily unavailable[&]Press the brake, click to start[&]If you need to park, please press the brake[&]Please press the brake[&]. If the vehicle is rolling[&], the slope is too steep, and the parking space cannot be recognized at the moment[&]has been paused. If you want to resume, you can release the brake[&]In reverse, Please pay attention to the safety of the surrounding environment[&][&]";


        String ss = "[&]请踩住刹车，点击开始[&]请松开刹车，开始泊车[&]请注意周围环境安全[&]泊车暂停，有障碍物阻挡[&]泊车已退出，请接管车辆[&]泊车已完成[&]泊车已退出[&]请注意周围环境安全[&]泊车暂停，有障碍物阻挡[&]泊出已退出[&]泊出已完成[&]请松开刹车，开始泊出[&]确认安全后，点击继续泊车[&]确认安全后，点击继续泊车[&]点击开始，帮你泊出[&][&]倒车中，请注意周围环境安全[&]车速过快，暂无法识别车位[&][&]找到车位，如需泊入请停车[&]泊车暂不可用[&]踩住刹车，点击开始[&]如需泊入，请踩刹车[&]请踩刹车，车辆溜车[&]坡度过大，暂无法识别车位[&]已暂停，如需恢复可松开刹车[&]倒车中，请注意周围环境安全[&][&][&][&][&][&]请注意后方剐蹭风险[&]正在探测车位内空间是否充足[&]车位有障碍物，请更换[&]请踩刹车，车辆溜车[&][&]泊车路径规划中[&]这个车位有点难，帮帮我吧";
        String[] strsz = ap_array_auto_parking3.split(";");
        String[] strsd = ap_array_auto_parkingAR.split(";");

        String[] strsen = ss.split("\\[&\\]");

        System.out.println(strsz.length);
    }
}
